apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.project }}
spec:
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: k6
            image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
            imagePullPolicy: Always
          restartPolicy: OnFailure
