apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ project }}
spec:
  schedule: "{{ schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: k6
            image: norgefajardo/test-k6:{{ tag }}
            imagePullPolicy: Always
          restartPolicy: OnFailure
